### ISSUE TITLE
Remove outdated portion of welcome email

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-id-broker#137]
Both the HTML and the plain test versions of the welcome email describe events that have already happened as being yet in the future:

https://github.com/silinternational/idp-id-broker/blob/7d677c76f53606edf9b112c1720ca3e08c33c2f4/application/common/mail/welcome.html.php#L32-L37

https://github.com/silinternational/idp-id-broker/blob/7d677c76f53606edf9b112c1720ca3e08c33c2f4/application/common/mail/welcome.text.php#L29-L34

I think we can simply remove those, leaving only the first sentence in that paragraph:
> Congratulations! You have logged into your new {$idpDisplayName} account for the first time.

**Comment by Schparky** [comment]
Addressed in #160
