### ISSUE TITLE
New endpoint for deactivating a user

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-id-broker#18]
Would it be worth having a more specific endpoint for deactivating a user? (Something like `PUT /user/{employee_id}/active`).

Since the two calls that ID Sync will need to make to the ID Broker are (1) create-or-update a user and (2) deactivate a user, it seems acceptable to have separate endpoints (rather than having the ID Broker receive both types of requests at the same endpoint, leaving it to have to sort out which is which).

The main driving factor, though, is that when deactivating a user there's no reason to be sending all the fields about the user... in fact, the ID Sync won't have any fields about the user. All it knows it that it asked the ID Store about that user and it got back the message that the user is no longer active / in existence. Therefore, it can't supply all the required fields to do a `POST /user/{employee_id}`.

Any objection to (or other thoughts about) adding a...
```
PUT /user/{employee_id}/active
{"active":"no"}
```
... endpoint for deactivating a user?

**Comment by forevermatt** [comment]
I suppose the other main option would be to simply enable the `PUT /user/{employee_id}` endpoint and make all fields optional.

**Comment by forevermatt** [comment]
The latter approach (using the `PUT /user/{employee_id} endpoint`) is the direction that PR #22 takes.

**Comment by wcjr** [comment]
ok, thanks!

**Comment by fillup** [comment]
I'm fine with what you guys discussed of it being a post on /user/{employee_id} with `active` in the body. I'd expect a `PUT` to support all fields as optional anyway so only providing `active` is fine.

**Comment by wcjr** [comment]
so @forevermatt , in order to keep track of the work that needs to happen for this, will you be adding another issue for the implementation?  I noticed #22 is just for the spec.

**Comment by forevermatt** [comment]
@wcjr Wait, the spec doesn't automatically make the code do exactly what we want? ;-)

I'm not very confident in my ability to manually find all of the places that the spec has changed since you started implementing the ID Broker, so I may also add an issue for comparing the finished implementation against the final spec. once we're done... but yes, I'll add an issue for this specific change.

**Comment by forevermatt** [comment]
Added #31 and #32.
