### ISSUE TITLE
Obfuscate any differences between failed authentications

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-id-broker#20]
We'll want to make sure that calls to `POST /authenticate` that are not acceptable (for whatever reason) all look identical. In other words, whether the username is wrong (i.e. no such user), the password is wrong, the user is inactive, or the user is locked, the request should take approximately the same amount of time to return and the response should be identical for all of those scenarios.

**Comment by wcjr** [comment]
relevant code:  

https://github.com/silinternational/idp-id-broker/blob/feature/initial-features/application/frontend/controllers/AuthenticationController.php#L25-L37

and

https://github.com/silinternational/idp-id-broker/blob/feature/initial-features/application/common/models/User.php#L83

**Comment by fillup** [comment]
Currently the errors are different if the user doesn't exist versus if the password was incorrect. The error displayed to the end user needs to be the same, but do we want it to be the same from the broker to auth app, or does it help auth app to know the difference between exists/doesn't and incorrect pw?

**Comment by forevermatt** [comment]
I don't think the auth. app gains anything by knowing that. In face, it's helpful if it doesn't know.

When checking a username/password combination, from a security standpoint we want there to be (as much as possible) no discernible difference for the requester between a non-existent user, a wrong password, a disabled user, etc.

The easiest/simplest way I see to do that is to not expose that difference to any part of the system. Since successfully concealing those differences takes some careful design, hiding the complexities of that design in a single place in a single piece of the system (the ID Broker, ideally in a single function somewhere like the `User` class) seems like it would be good approach.

**Comment by wcjr** [comment]
@forevermatt @fillup FYI, I'm going to leave the error message blank and will also ensure even system, runtime errors come out as a generic bad request, i.e., those that might've been 500 will also come out as a 400.

**Comment by forevermatt** [comment]
@wcjr Okay. At the moment, I would think that (other than "acceptable credentials" and "unacceptable credentials"), the one other useful response would be "something went wrong, I don't know whether the credentials were acceptable" (meaning that 500 errors would be distinguishable from 400 errors). I'll leave that to you for now, though, since you're obviously much more in the middle of that context than I am.

**Comment by wcjr** [comment]
np, easy enough to distinguish them.

**Comment by forevermatt** [comment]
Since part of this issue (preventing timing attacks) is going to be addressed through a later change, do you mind if I re-open this until that additional piece is also done?

**Comment by wcjr** [comment]
that's fine, however that was done in this PR (it seems you didn't see that yet):  https://github.com/silinternational/idp-id-broker/pull/37

**Comment by forevermatt** [comment]
@wcjr According to the [AuthenticationController](https://github.com/silinternational/idp-id-broker/blob/develop/application/frontend/controllers/AuthenticationController.php#L23), it still looks like calls for non-existent users will bypass the timing attack protection (because `validate()` isn't called).

**Comment by wcjr** [comment]
excellent catch, I'll fix that.
