### ISSUE TITLE
Button label is now "Replace", not "Create"

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-id-broker#214]
https://github.com/silinternational/idp-id-broker/blob/0d4023d609a8bd53311b23a4f0ad098ce9de9383/application/common/mail/refresh-backup-codes.html.php#L45

The email reminding someone to get a new set of Printable Backup Codes says to click on the button labelled create, but the correct button is actually now labelled replace. Since this email is specific to refreshing someone's backup codes, I think we could simply change that word in this email template file to fix this.

**Comment by Schparky** [comment]
Agreed. I'll take care of it. Thanks.

**Comment by forevermatt** [comment]
Fixed by #215
