### ISSUE TITLE
Should a successful `POST /user` return anything?

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-id-broker#25]
Currently the RAML spec for this API says that a successful `POST /user` will return a `200`, but it doesn't mention any response body. Should this return anything (I don't see a need to) or, optionally, should it return a `204` (or is a `200` fine)?

**Comment by wcjr** [comment]
If you don't mind, I'd prefer to stick to normal REST conventions on this and return the user info.  Is that ok?

**Comment by forevermatt** [comment]
@wcjr Sounds good. @fillup actually recommended the same thing.
