### ISSUE TITLE
Ensure `last_synced_utc` is updated appropriately

### ISSUE THREAD

**Issue by wcjr** [silinternational/idp-id-broker#27]
This field should only ever be updated when a sync has occurred, not password changes.  At this time, that might mean only when a `POST` has occurred.

**Comment by forevermatt** [comment]
`PUT`s from the ID Sync (updating an existing user) would also qualify. Since we have a different endpoint for updating a password, I think we can treat all `POST /user` and `PUT /user/{employee_id}` calls as updating `last_synced_utc`. Does that sound right to you?

**Comment by wcjr** [comment]
Sounds right to me.

**Comment by wcjr** [comment]
I'm assuming `last_changed_utc` should change any time any value changes on the row and it's **not** tied in any way to whether a change occurred as part of a sync or not, is that your understanding as well @fillup @forevermatt ?

**Comment by forevermatt** [comment]
@wcjr Yes
