### ISSUE TITLE
mysql bug needs to be protected against

### ISSUE THREAD

**Issue by wcjr** [silinternational/idp-id-broker#29]
https://github.com/yiisoft/yii2/issues/7066

```
SELECT * FROM `user` WHERE employee_id = false
```
when `employee_id` has a value of `123` will not return any rows, however with a value of `abc123`, it WILL return something!!!  This can show up in `ActiveRecord::findOne()` calls where user input is being sent in as a value to match.  Simply casting that user input to a `(string)` will protect.

This needs to be done in the UserController and tests need to be written to check for it.

**Comment by wcjr** [comment]
Additional resources:

https://bugs.mysql.com/bug.php?id=42241
https://dev.mysql.com/doc/refman/5.7/en/type-conversion.html

**Comment by fillup** [comment]
It might be worth after the findOne call to check the returned object to ensure the searched value matches what we searched, so something like:

```php
$username = 'jimmy';
$user = User::findOne(['username' => $username]);
if ($user !== null && $user->username == $username) {
 ...
}
```

That way if some bug or trick allowed the db to return the wrong record we're still verifying we got what we wanted.

**Comment by Schparky** [comment]
Not sure if something may have changed in the past couple years, but I'm not able to reproduce this by anything I provide from the consumer. The parameter is presented to the controller as a string, even without a type hint. So this: 
```php
    public function actionView($employeeId) // GET /user/abc123
    { 
        die(var_dump($employeeId));
```
prints

> /data/frontend/controllers/UserController.php:18:string 'false' (length=5)

or 

> /data/frontend/controllers/UserController.php:18:string '0' (length=1)

Now, I can see this bug might arise when using data received in a json request body, such as `PUT /method/{uid}/verify` so definitely something to watch out for.
