### ISSUE TITLE
401 vs. 404

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-id-broker#3]
For requests to non-existent endpoints (such as `/fake`), we currently return a `404`, and only return a `401` if they are requesting a real endpoint (such as `/user/`).

My first inclination is to return `401` for any unauthorized request, and only return a `404` for authorized requests to a non-existent endpoint.

Thoughts?

**Comment by wcjr** [comment]
This is a B2B system so hopefully we're not guarding against a prevalent use case, however I agree with you and prefer this idea *if* we're able to tweak Yii's lifecycle without much effort, i.e., can we change Yii's ordering of authn and `urlManager` exceptions?  Presumably yes, everything seems to be configurable ;-)
