### ISSUE TITLE
Add separate endpoints for creating vs. updating a user

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-id-broker#31]
Per our changes to the spec in #22, we need to split out our endpoints as follows:

- `POST /user` is just for creating a new user
- `PUT /user/{employee_id}` will be for updating a user.

**Comment by wcjr** [comment]
though not explicit in this issue, `GET /user` will also be added.

**Comment by wcjr** [comment]
Regarding `GET /user` (https://github.com/silinternational/idp-id-broker/blob/develop/api.raml#L234-L259).

Default behavior out-of-the-box, i.e., `GET /user` without any `fields` would give the following data for each user:

```json
[
    {
        "employee_id": "123",
        "first_name": "Shep",
        "last_name": "Clark",
        "display_name": "Shep Clark",
        "username": "shep_clark",
        "email": "shep_clark@example.org",
        "active": "yes",
        "locked": "no"
    }
],
```

I think I remember a proposal about only including the `employee_id` if nothing was provided, is that still accurate behavior?

**Comment by wcjr** [comment]
In conversation with @fillup , we're agreed to leave the out-of-the-box for now.  Should any problems arise later, we'll bring in some `fields` behavior.
