### ISSUE TITLE
Force HTTPS?

### ISSUE THREAD

**Issue by wcjr** [silinternational/idp-id-broker#38]
Noticed `HTTPS` in https://github.com/silinternational/idp-id-broker/blob/develop/api.raml#L3.  We are not currently enforcing this from an app perspective, should we be?

**Comment by forevermatt** [comment]
I think so. This will only be accessible on the "internal" network (of this IdP-in-a-Box system), so I don't know whether a load-balancer will be involved, but either way we don't want any `HTTP` traffic to the ID Broker since some of that traffic will contain plaintext passwords.

**Comment by wcjr** [comment]
fine with me, @fillup do we have an example of setting up "dummy" certs for local testing?  When it comes to certs, the only thing I have in memory is "start at https://letsencrypt.org".

I'll need to put some enforcement logic in place once we have all the infrastructure in the project to support SSL.

- [ ] establish local certs
- [ ] enforce HTTPS within app

**Comment by wcjr** [comment]
fyi @forevermatt , @fillup wants to hold off on this for now.  If we adopt such an approach internally, we will do it broadly at an "enterprise" level.
