### ISSUE TITLE
Pashword re-hashing

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-id-broker#4]
As computers continue to advance, the time-cost of calculating our password hashes will probably steadily decrease. As per the example at...
<https://paragonie.com/blog/2016/02/how-safely-store-password-in-2016#php-bcrypt>
... of using PHP's built-in `password_hash()` and `password_verify()` functions, it is apparently a good practice to check each correct password to see if we should regenerate the hash. (This would only happen if we raised the `cost`, such as from 10 to 12, and had just verified a hash generated using the old cost of 10.)

Is it better to do this lazy-loading style of password re-hashing, or would it be worth setting up some batch process to be able to go through and rehash passwords on command once we've released an update to ID Broker that sets a higher password hash `cost`?

**Comment by wcjr** [comment]
Thanks for capturing this!  

FWIW, I initially prefer the idea of doing it all at once via a batch for a couple of reasons; to keep additional housekeeping logic out of the "app" and to ensure **all** the hashes are at the same level of maturity at any given time.  Developing such a process independently of the app might even allow us to build it for use on other projects...

**Comment by forevermatt** [comment]
@wcjr That makes sense. My two concerns are (1) the examples I see from people who know more about this than I do seem to use the lazy-loading approach (for whatever that's worth), and (2) a bug in our batch-rehashing process could lock everyone in the organization out all at once. If there were a bug in our lazy-loading approach, it would cause problems fast enough for us to know right away, but slow enough that it wouldn't stop the entire organization in it's tracks (hopefully). A lesser concern is that code run frequently and automatically is easier to trust and depend on than code run manually and infrequently, so batch jobs (especially if rarely applicable) seem more risky to me. However, I'm welcome to other perspectives if you see something I've missed.

**Comment by wcjr** [comment]
yeah, those are some great points Matt, let's see if there are any opposing thoughts from @fillup otherwise we can go with your approach.

**Comment by fillup** [comment]
I'd vote to start with lazy processing one off, and we can consider a batch process as a means for responding to security incidents or something.

**Comment by devon-sil** [comment]
@forevermatt Was this completed back then?  I see some code that makes me thing it is done.

**Comment by briskt** [comment]
It was done fairly recently: https://github.com/silinternational/idp-id-broker/releases/tag/6.6.5
