### ISSUE TITLE
Namespace convention wrong

### ISSUE THREAD

**Issue by wcjr** [silinternational/idp-id-broker#40]
Namespaces should be corrected to `Sil\Idp\IdBroker\...`

**Comment by fillup** [comment]
That isn't true, for a full application like this you don't need to use namespaces like that. Only clients/libraries need that. You can leave it with the defaults of `common\`, `frontend\`, etc.

**Comment by wcjr** [comment]
oh ok, thanks for the clarificaton, that makes things easier.  FYI @forevermatt

**Comment by forevermatt** [comment]
Oops... sorry I led you wrong on that one, @wcjr.
