### ISSUE TITLE
"Stale" users

### ISSUE THREAD

**Issue by longrunningprocess** [silinternational/idp-id-broker#5]
Imagine a user sits in this database without having its `last_synced_date` updated in the last 5 syncs for example.  Do we need logic in place to purge, i.e., `active=no`, this user? @fillup @forevermatt

**Comment by forevermatt** [comment]
@wcjr One possibility that @lvail mentioned is that our incremental updates could retrieve all users not synced since (timestamp), and that would let us know about users that should be deactivated (just like out batch update would deactivate all users not in the list from ID Store at all).

**Comment by fillup** [comment]
We talked about having a cron that checks for users not synced in past 48 hours and foreach does individual syncs.

**Comment by fillup** [comment]
Sorry, to be more specific:

1. `id-broker` should have cron job looking for "stale" users.
2. For each stale user, call `id-sync` webhook for an individual user sync/update.
3. If webhook call to `id-sync` does not respond successfully, trigger alert.

**Comment by wcjr** [comment]
Does the work we did in https://github.com/silinternational/idp-id-broker/pull/74 change anything about this approach in your all's minds @fillup @forevermatt ?

**Comment by forevermatt** [comment]
I don't think so, @wcjr. Those changes in #74 seem to just be focused on password expiration dates, whereas this is about triggering an individual sync for users that haven't been synced recently.

**Comment by wcjr** [comment]
ok, sounds good.
