### ISSUE TITLE
URL routing problems

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-id-broker#54]
For some reason, doing a `POST /user/` (with a trailing slash) gets mapped to `UserController->actionIndex()`, returning the list of all users.

In addition, it seems to accept things like `POST /user/create` and map it to `UserController->actionCreate()`, even though we neither want that nor have a URL rule pattern that should cause that to work. That should return a `404` as far as I can tell.

Given that those URL paths are being routed to controller actions without us specifically telling them to, we may have this problem in other Yii2 websites.

**Comment by devon-sil** [comment]
Adding to backlog.

**Comment by devon-sil** [comment]
This issue hasn't seemed to crop up in quite some time, so it doesn't appear to be an edge case we need to worry about.
