### ISSUE TITLE
Send New User Invitation emails when appropriate

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-id-broker#84]
When...
- a new user is created, **and**
- a New User Invitation email has not yet been sent to them, **and** 
- this ID Broker is configured to send New User Invitation emails

... then cause a New User Invitation email to be sent to the user (via the Email Service).

Depends on #83.

**Comment by forevermatt** [comment]
Partially met by #87, but the content of the email is still lacking.

**Comment by Schparky** [comment]
Addressed by #98
