### ISSUE TITLE
Send Welcome emails when appropriate

### ISSUE THREAD

**Issue by forevermatt** [silinternational/idp-id-broker#85]
When...
- a password is recorded for a user that previously lacked a password, **and**
- a welcome email has not yet been sent to them, **and** 
- this ID Broker is configured to send welcome emails

... then cause a welcome email to be sent to the user (via the Email Service).

Depends on #83.

**Comment by forevermatt** [comment]
Partially met by #87, but the content of the email is still lacking.

**Comment by Schparky** [comment]
Addressed by #102 and later by #160
